# image will be published to ghcr.io/<user>/<name>
name: perrrkele
# description will be included in the image's metadata
description: Laptop / Intel CPU / Intel GPU / GNOME

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://raw.githubusercontent.com/cig0/ublue-os/live/custom/sublime-text.repo
    install:
      - 'gcc-c++'
      - ansible
      - awscli2
      - bemenu
      - blender
      - borgbackup
      - bridge-utils
      - bat
      - btop
      - btrfsd
      - cargo
      - code
      - difftastic
      - dnstracer
      - dua-cli
      - duf
      - edk2-ovmf
      - emacs
      - perl-Image-ExifTool
      - fd-find
      - fdupes
      - fuzzel
      - fzf
      - gh
      - git-lfs
      - glab
      - glances
      - golang
      - goaccess
      - golang-x-tools-gopls
      - grpcurl
      # Needs: fedora-cisco-openh264.repo
      #- gstreamer1-plugin-openh264
      - gstreamer1-plugin-libav
      - gstreamer1-plugin-mpg123
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-free-fluidsynth
      - gstreamer1-plugins-ugly
      - gstreamer1-vaapi
      - guestfs-tools
      - httpie
      - hugo
      - hyperfine
      - hyprland
      - imhex
      - imhex-patterns
      - intel-gpu-tools
      - inxi
      - iotop
      - krusader
      - libnotify
      - libvirt
      - libvirt-daemon
      - libvirt-daemon-config-network
      - libvirt-daemon-driver-interface
      - libvirt-daemon-driver-network
      - libvirt-daemon-driver-nwfilter
      - libvirt-daemon-driver-qemu
      - libvirt-daemon-driver-secret
      - libvirt-daemon-driver-storage-core
      - lftp
      - lnav
      - lynis
      - mc
      - mold
      - ncdu # Needs urgent version bump!
      - neofetch
      - neovim
      - nfs-utils
      - nmap
      - nodejs
      - oathtool
      - pinentry-tty
      - podman-compose
      - powertop
      - python3-ipython
      - python3-pip
      - python3-psutil
      - qemu-kvm
      - ripgrep
      - rpcbind
      - s-tui
      - shellcheck
      - strace
      #- sublime-merge
      #- sublime-text
      - syncthing
      - tcpdump
      - telnet
      - tesseract
      - tokei
      - translate-shell
      - ugrep # Needs urgent version bump!
      - vagrant
      - vdpauinfo
      - virt-install
      - virt-manager
      - virt-top
      - virt-viewer
      - waydroid
      - waydroid-selinux
      - weechat
      - wl-clipboard
      - yakuake
      - zoxide
    remove:
      # - firefox # default firefox removed in favor of flatpak
      # - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - justfiles # add "!include /usr/share/ublue-os/just/100-bling.just"
                  # in your custom.just (added by default) or local justfile
      - nix-installer # shell shortcuts for determinate system's nix installers
      # - ublue-os-wallpapers
      - ublue-update # https://github.com/ublue-os/ublue-update
      # - 1password # install 1Password (stable) and `op` CLI tool
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm
      # - gnome-vrr # enables gnome-vrr for your image
      # - container-tools # installs container-related tools onto /usr/bin: kind, kubectx, docker-compose and kubens
      - laptop # installs TLP and configures your system for laptop usage
      - flatpaksync # allows synchronization of user-installed flatpaks, see separate documentation section

  - type: yafti # if included, yafti and it's dependencies (pip & libadwaita)
                #  will be installed and set up
    custom-flatpaks: # this section is optional
      - KDE Akregator: org.kde.akregator
      - KDE digiKam: org.kde.digikam
      - KDE Gwenview: org.kde.gwenview
      - KDE Kcalc: org.kde.kcalc
      - KDE KColorChooser: org.kde.kcolorchooser
      - KDE KDiff3: org.kde.kdiff3
      - KDE Kompare: org.kde.kompare
      - KDE Krita: org.kde.krita
      - KDE Neochat: org.kde.neochat
      - KDE Okular: org.kde.okular
      - ArmCord: xyz.armcord.ArmCord
      - ASCII Draw: io.github.nokse22.asciidraw
      - Brave: com.brave.Browser
      - Darktable: org.darktable.Darktable
      - Flatseal: com.github.tchx84.Flatseal
      - Flatsweep: io.github.giantpinkrobots.flatsweep
      - Inkscape: org.inkscape.Inkscape
      - KeePassXC: org.keepassxc.KeePassXC
      - Letterpress: io.gitlab.gregorni.Letterpress
      - LightZone: io.github.ktgw0316.LightZone
      - LibreOffice: org.libreoffice.LibreOffice
      - MPV: io.mpv.Mpv
      - Nheko: io.github.NhekoReborn.Nheko
      - Nicotine: org.nicotine_plus.Nicotine
      - OpenLens: dev.k8slens.OpenLens
      - Parabolic: org.nickvision.tubeconverter
      - Podman Desktop: io.podman_desktop.PodmanDesktop
      - Shortwave: de.haeckerfelix.Shortwave
      - Slack: com.slack.Slack
      - Telegram: org.telegram.desktop
      - The GIMP: org.gimp.GIMP
      - Todoist: com.todoist.Todoist
      - Tor Browser: com.github.micahflee.torbrowser-launcher
      - Ultimate Media Downloader: com.ktechpit.ultimate-media-downloader
      - Vorta: com.borgbase.Vorta
      - Warehouse: io.github.flattool.Warehouse
      - YouTube Downloader: io.github.aandrew_me.ytdn
      - Zoom: us.zoom.Zoom

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh

